Vagrant.configure("2") do |config|

    config.vm.box = "spox/ubuntu-arm"
    config.vm.box_check_update = false   

    config.vm.provider "vmware_fusion" do |vb|
        vb.memory = 2048
        vb.cpus = 2
    end

    config.vm.define "dtome-peS" do |server|
        server.vm.hostname = "dtome-peS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.synced_folder "./scripts", "/vagrant/scripts"
        server.vm.synced_folder "./confs", "/vagrant/confs"
        server.vm.provision "shell", privileged: true, path: "scripts/setup.sh", env: {"KUBECONFIG" => "/etc/rancher/k3s/k3s.yaml"}
    end

end
