# confs/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/romz8/InceptionOfThings_CICD  #GitHub repo with Wils app 
    targetRevision: main  # Branch name
    path: manifests       # Folder containing your YAML files (deployment.yaml, service.yaml)
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
