#configuring the first VM - Server 1
Vagrant.configure("2") do |config|
    config.vm.define "rjobertS" do |server|
        server.vm.box = "generic/alpine317"
        #config.vm.box = "spox/ubuntu-arm64" #"ubuntu/focal64" doesn't work on vmware for mac 
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.hostname = "rjobertS"
        config.vm.synced_folder '.', '/vagrant'
        server.vm.provider "virtualbox" do |vmw1| #replace by "virtualbox" on campus VM
            vmw1.memory = 1024
            vmw1.cpus = 1
            end
        server.vm.provision "shell", path: "./scripts/rjobertS_setup.sh"
    end
    config.vm.define "rjobertSW" do |worker|
        worker.vm.box = "generic/alpine317"
        config.vm.synced_folder '.', '/vagrant'
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.hostname = "rjobertSW"
        worker.vm.provider "virtualbox" do |vmw2| #replace by "virtualbox" on campus VM
            vmw2.memory = 1024
            vmw2.cpus = 1
            end
        worker.vm.provision "shell", path: "./scripts/rjobertSW_setup.sh"
    end
end